services:
  api: &main_app
    build:
      context: .
      dockerfile: ./Dockerfile
    image: gobble_cube:${GOBBLE_CUBE_VERSION:-latest}
    restart: always
    env_file:
      - .env
    environment:
      GOBBLE_CUBE_HOST: 0.0.0.0
      GOBBLE_CUBE_DB_FILE: /db_data/db.sqlite3
    volumes:
      - gobble_cube-db-data:/db_data/



volumes:
  gobble_cube-db-data:
    name: gobble_cube-db-data
